// B4.6 relic pools + acquisition. Pool goldens are independently captured from
// the live §2.5 oracle block (campaign b14_accept, STS00001..00003); expected
// arrays are literals, not generated by the implementation under test.

#include <array>
#include <cstdint>
#include <limits>

#include "gtest/gtest.h"

#include "sts/engine/cards.hpp"
#include "sts/engine/relic_pools.hpp"
#include "sts/engine/run_advance.hpp"

namespace sts::engine {
namespace {

constexpr int kCommon = static_cast<int>(RelicPool::COMMON);
constexpr int kRare = static_cast<int>(RelicPool::RARE);
constexpr int kBoss = static_cast<int>(RelicPool::BOSS);

template <std::size_t N>
void expect_pool(const RunState& rs, RelicPool pool,
                 const std::array<RelicId, N>& expected) {
    const int p = static_cast<int>(pool);
    ASSERT_EQ(rs.relic_pool_count[p], N);
    for (std::size_t i = 0; i < N; ++i) {
        EXPECT_EQ(rs.relic_pools[p][i], static_cast<uint16_t>(expected[i]))
            << "pool index " << i;
    }
}

template <std::size_t N>
void set_pool(RunState& rs, RelicPool pool,
              const std::array<RelicId, N>& ids) {
    const int p = static_cast<int>(pool);
    rs.relic_pool_count[p] = static_cast<uint8_t>(N);
    for (std::size_t i = 0; i < N; ++i) {
        rs.relic_pools[p][i] = static_cast<uint16_t>(ids[i]);
    }
}

constexpr std::array<RelicId, 33> kOracleSeed1{{
    RelicId::STRAWBERRY, RelicId::NUNCHAKU, RelicId::PRESERVED_INSECT,
    RelicId::ANCHOR, RelicId::JUZU_BRACELET, RelicId::VAJRA,
    RelicId::CERAMIC_FISH, RelicId::DREAM_CATCHER, RelicId::BOOT,
    RelicId::PEN_NIB, RelicId::WAR_PAINT, RelicId::AKABEKO,
    RelicId::BAG_OF_MARBLES, RelicId::WHETSTONE, RelicId::RED_SKULL,
    RelicId::MEAL_TICKET, RelicId::LANTERN, RelicId::MAW_BANK,
    RelicId::TINY_CHEST, RelicId::SMILING_MASK, RelicId::HAPPY_FLOWER,
    RelicId::BLOOD_VIAL, RelicId::ODDLY_SMOOTH_STONE,
    RelicId::CENTENNIAL_PUZZLE, RelicId::BAG_OF_PREPARATION,
    RelicId::ART_OF_WAR, RelicId::TOY_ORNITHOPTER, RelicId::ORICHALCUM,
    RelicId::ANCIENT_TEA_SET, RelicId::REGAL_PILLOW, RelicId::OMAMORI,
    RelicId::POTION_BELT, RelicId::BRONZE_SCALES,
}};

constexpr std::array<RelicId, 33> kOracleSeed2{{
    RelicId::ODDLY_SMOOTH_STONE, RelicId::BAG_OF_PREPARATION,
    RelicId::POTION_BELT, RelicId::MAW_BANK, RelicId::STRAWBERRY,
    RelicId::TOY_ORNITHOPTER, RelicId::OMAMORI, RelicId::CERAMIC_FISH,
    RelicId::PEN_NIB, RelicId::ART_OF_WAR, RelicId::AKABEKO,
    RelicId::CENTENNIAL_PUZZLE, RelicId::BRONZE_SCALES, RelicId::VAJRA,
    RelicId::HAPPY_FLOWER, RelicId::PRESERVED_INSECT, RelicId::BOOT,
    RelicId::ANCHOR, RelicId::NUNCHAKU, RelicId::LANTERN,
    RelicId::REGAL_PILLOW, RelicId::DREAM_CATCHER,
    RelicId::ANCIENT_TEA_SET, RelicId::ORICHALCUM, RelicId::SMILING_MASK,
    RelicId::WHETSTONE, RelicId::JUZU_BRACELET, RelicId::BLOOD_VIAL,
    RelicId::WAR_PAINT, RelicId::BAG_OF_MARBLES, RelicId::TINY_CHEST,
    RelicId::MEAL_TICKET, RelicId::RED_SKULL,
}};

constexpr std::array<RelicId, 33> kOracleSeed3{{
    RelicId::CERAMIC_FISH, RelicId::ANCIENT_TEA_SET, RelicId::WHETSTONE,
    RelicId::BOOT, RelicId::ANCHOR, RelicId::SMILING_MASK,
    RelicId::MEAL_TICKET, RelicId::BAG_OF_MARBLES, RelicId::JUZU_BRACELET,
    RelicId::AKABEKO, RelicId::PEN_NIB, RelicId::REGAL_PILLOW,
    RelicId::BRONZE_SCALES, RelicId::ODDLY_SMOOTH_STONE,
    RelicId::CENTENNIAL_PUZZLE, RelicId::TINY_CHEST, RelicId::NUNCHAKU,
    RelicId::BAG_OF_PREPARATION, RelicId::POTION_BELT,
    RelicId::STRAWBERRY, RelicId::HAPPY_FLOWER, RelicId::OMAMORI,
    RelicId::LANTERN, RelicId::ART_OF_WAR, RelicId::WAR_PAINT,
    RelicId::PRESERVED_INSECT, RelicId::RED_SKULL, RelicId::ORICHALCUM,
    RelicId::DREAM_CATCHER, RelicId::MAW_BANK, RelicId::BLOOD_VIAL,
    RelicId::TOY_ORNITHOPTER, RelicId::VAJRA,
}};

TEST(RelicPools, OracleCommonPoolOrdersMatchThreeLiveSeeds) {
    struct Case {
        int64_t seed;
        const std::array<RelicId, 33>* pool;
        int64_t s0;
        int64_t s1;
    };
    const Case cases[] = {
        {1790050543751LL, &kOracleSeed1, -6368056192266778531LL,
         -2945499761529171947LL},
        {1790050543752LL, &kOracleSeed2, -2647188671728073487LL,
         -7059635356477542313LL},
        {1790050543753LL, &kOracleSeed3, 5762858951679628331LL,
         -7642149939435051131LL},
    };
    for (const Case& c : cases) {
        RunState rs{};
        rs.relic_rng = from_seed(c.seed);
        initialize_relic_pools(rs);
        expect_pool(rs, RelicPool::COMMON, *c.pool);
        EXPECT_EQ(rs.relic_rng.counter, 5);
        EXPECT_EQ(rs.relic_rng.s0, static_cast<uint64_t>(c.s0));
        EXPECT_EQ(rs.relic_rng.s1, static_cast<uint64_t>(c.s1));
        for (int p = 1; p < kRelicTierCount; ++p) {
            EXPECT_EQ(rs.relic_pool_count[p], 0)
                << "tier content belongs to B3.25-B3.27, p=" << p;
        }
    }
}

TEST(RelicPools, InitializesAllFiveWithFiveDrawsEvenWhenFourAreEmpty) {
    RunState rs{};
    rs.relic_rng = from_seed(77);
    RngStream expected = rs.relic_rng;
    for (int i = 0; i < 5; ++i) {
        (void)random_long(expected);
    }
    initialize_relic_pools(rs);
    EXPECT_EQ(rs.relic_pool_count[kCommon], 33);
    EXPECT_EQ(rs.relic_rng.counter, 5);
    EXPECT_EQ(rs.relic_rng.s0, expected.s0);
    EXPECT_EQ(rs.relic_rng.s1, expected.s1);
}

TEST(RelicPools, Trap15FrontVsEndPopOppositeSides) {
    constexpr std::array ids{RelicId::ANCHOR, RelicId::BLOOD_VIAL,
                             RelicId::VAJRA};
    RunState front{};
    RunState end{};
    set_pool(front, RelicPool::COMMON, ids);
    set_pool(end, RelicPool::COMMON, ids);
    EXPECT_EQ(return_random_relic_key(front, RelicTier::COMMON), RelicId::ANCHOR);
    EXPECT_EQ(return_end_random_relic_key(end, RelicTier::COMMON), RelicId::VAJRA);
    EXPECT_EQ(front.relic_pool_count[kCommon], 2);
    EXPECT_EQ(end.relic_pool_count[kCommon], 2);
}

TEST(RelicPools, BossEndPathStillPopsFront) {
    constexpr std::array ids{RelicId::ANCHOR, RelicId::VAJRA};
    RunState rs{};
    set_pool(rs, RelicPool::BOSS, ids);
    EXPECT_EQ(return_end_random_relic_key(rs, RelicTier::BOSS), RelicId::ANCHOR);
}

TEST(RelicPools, FailedFrontCanSpawnRecheckSwitchesToEnd) {
    constexpr std::array ids{RelicId::TINY_CHEST, RelicId::BLOOD_VIAL,
                             RelicId::ANCHOR};
    RunState rs{};
    set_pool(rs, RelicPool::COMMON, ids);
    const RelicSpawnContext late{36, false, false};
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::COMMON, late),
              RelicId::ANCHOR);
    ASSERT_EQ(rs.relic_pool_count[kCommon], 1);
    EXPECT_EQ(rs.relic_pools[kCommon][0],
              static_cast<uint16_t>(RelicId::BLOOD_VIAL));
}

TEST(RelicPools, ExhaustedPoolsFallBackToCirclets) {
    RunState rs{};
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::RARE), RelicId::CIRCLET);
    EXPECT_EQ(return_end_random_relic_key(rs, RelicTier::BOSS),
              RelicId::CIRCLET);
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::COMMON), RelicId::CIRCLET);
}

TEST(RelicPools, TierRollTableIsExactly50_33_17) {
    int common = 0;
    int uncommon = 0;
    int rare = 0;
    for (int roll = 0; roll < 100; ++roll) {
        switch (relic_tier_for_roll(roll)) {
            case RelicTier::COMMON: ++common; break;
            case RelicTier::UNCOMMON: ++uncommon; break;
            case RelicTier::RARE: ++rare; break;
            default: FAIL() << "unexpected tier";
        }
    }
    EXPECT_EQ(common, 50);
    EXPECT_EQ(uncommon, 33);
    EXPECT_EQ(rare, 17);
    EXPECT_EQ(relic_tier_for_roll(49), RelicTier::COMMON);
    EXPECT_EQ(relic_tier_for_roll(50), RelicTier::UNCOMMON);
    EXPECT_EQ(relic_tier_for_roll(82), RelicTier::UNCOMMON);
    EXPECT_EQ(relic_tier_for_roll(83), RelicTier::RARE);
}

TEST(RelicAcquisition, AppendsInOrderAndAppliesSheetEffects) {
    RunState rs{};
    rs.hp = 60;
    rs.max_hp = 80;
    rs.potion_slots = 2;
    RngStream misc = from_seed(1);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::STRAWBERRY),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::POTION_BELT),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(rs.relic_count, 2);
    EXPECT_EQ(rs.relics[0].relic_id, static_cast<uint16_t>(RelicId::STRAWBERRY));
    EXPECT_EQ(rs.relics[1].relic_id, static_cast<uint16_t>(RelicId::POTION_BELT));
    EXPECT_EQ(rs.hp, 67);
    EXPECT_EQ(rs.max_hp, 87);
    EXPECT_EQ(rs.potion_slots, 4);
}

TEST(RelicAcquisition, ConstructorAndOnEquipCountersAreExact) {
    RunState rs{};
    RngStream misc = from_seed(2);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::BURNING_BLOOD),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::OMAMORI),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::TINY_CHEST),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::NUNCHAKU),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.relics[0].counter, -1);
    EXPECT_EQ(rs.relics[1].counter, 2);
    EXPECT_EQ(rs.relics[2].counter, 0);
    EXPECT_EQ(rs.relics[3].counter, 0);
}

TEST(RelicAcquisition, OrdinaryDuplicatesAppendButCircletStacks) {
    RunState rs{};
    RngStream misc = from_seed(3);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.relic_count, 2);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(rs.relic_count, 3);
    EXPECT_EQ(rs.relics[2].counter, 1);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::CIRCLET_STACKED);
    EXPECT_EQ(rs.relic_count, 3);
    EXPECT_EQ(rs.relics[2].counter, 2);
}

TEST(RelicAcquisition, FixedRelicCapFailsWithoutMutation) {
    RunState rs{};
    RngStream misc = from_seed(4);
    for (int i = 0; i < kRelicCap; ++i) {
        ASSERT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
                  RelicAcquireResult::ACQUIRED);
    }
    const int16_t hp = rs.hp;
    const int16_t max_hp = rs.max_hp;
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::STRAWBERRY),
              RelicAcquireResult::RELIC_CAP_REACHED);
    EXPECT_EQ(rs.relic_count, kRelicCap);
    EXPECT_EQ(rs.hp, hp);
    EXPECT_EQ(rs.max_hp, max_hp);
}

TEST(RelicAcquisition, WarPaintAndWhetstoneUseMiscRngJdkShuffle) {
    RunState rs{};
    constexpr CardId deck[] = {
        CardId::STRIKE, CardId::STRIKE, CardId::STRIKE, CardId::STRIKE,
        CardId::STRIKE, CardId::DEFEND, CardId::DEFEND, CardId::DEFEND,
        CardId::DEFEND, CardId::BASH,
    };
    rs.master_deck_count = 10;
    for (uint16_t i = 0; i < 10; ++i) {
        rs.master_deck[i].card_id = static_cast<uint16_t>(deck[i]);
    }
    RngStream misc = from_seed(1234);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::WAR_PAINT),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.master_deck[7].upgrade, 1);
    EXPECT_EQ(rs.master_deck[8].upgrade, 1);
    EXPECT_EQ(rs.master_deck[5].upgrade, 0);
    EXPECT_EQ(rs.master_deck[6].upgrade, 0);

    EXPECT_EQ(acquire_relic(rs, misc, RelicId::WHETSTONE),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.master_deck[4].upgrade, 1);
    EXPECT_EQ(rs.master_deck[0].upgrade, 1);
    EXPECT_EQ(rs.master_deck[1].upgrade, 0);
    EXPECT_EQ(rs.master_deck[9].upgrade, 0);
    EXPECT_EQ(misc.counter, 2);
}

TEST(RelicAcquisition, CircletCounterCapacityIsExplicit) {
    RunState rs{};
    RngStream misc = from_seed(5);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::ACQUIRED);
    rs.relics[0].counter = std::numeric_limits<int16_t>::max();
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::COUNTER_CAP_REACHED);
    EXPECT_EQ(rs.relic_count, 1);
}

TEST(RelicPools, RunBeginPopulatesCommonPoolWithoutChangingFiveDrawOracle) {
    const RunController rc = run_begin(1790050543751LL, 20);
    expect_pool(rc.run, RelicPool::COMMON, kOracleSeed1);
    EXPECT_EQ(rc.run.relic_rng.counter, 5);
    ASSERT_EQ(rc.run.relic_count, 1);
    EXPECT_EQ(rc.run.relics[0].relic_id,
              static_cast<uint16_t>(RelicId::BURNING_BLOOD));
    EXPECT_EQ(rc.run.relics[0].counter, -1);
}

}  // namespace
}  // namespace sts::engine
