// B4.6 relic pools + acquisition. Pool goldens are independently captured from
// the live §2.5 oracle block (campaign b14_accept, STS00001..00003); expected
// arrays are literals, not generated by the implementation under test.

#include <array>
#include <cstdint>
#include <limits>

#include "gtest/gtest.h"

#include "sts/engine/cards.hpp"
#include "sts/engine/relic_pools.hpp"
#include "sts/engine/run_advance.hpp"
#include "sts/engine/run_deck.hpp"

namespace sts::engine {
namespace {

constexpr int kCommon = static_cast<int>(RelicPool::COMMON);
constexpr int kRare = static_cast<int>(RelicPool::RARE);
constexpr int kBoss = static_cast<int>(RelicPool::BOSS);

template <std::size_t N>
void expect_pool(const RunState& rs, RelicPool pool,
                 const std::array<RelicId, N>& expected) {
    const int p = static_cast<int>(pool);
    ASSERT_EQ(rs.relic_pool_count[p], N);
    for (std::size_t i = 0; i < N; ++i) {
        EXPECT_EQ(rs.relic_pools[p][i], static_cast<uint16_t>(expected[i]))
            << "pool index " << i;
    }
}

template <std::size_t N>
void set_pool(RunState& rs, RelicPool pool,
              const std::array<RelicId, N>& ids) {
    const int p = static_cast<int>(pool);
    rs.relic_pool_count[p] = static_cast<uint8_t>(N);
    for (std::size_t i = 0; i < N; ++i) {
        rs.relic_pools[p][i] = static_cast<uint16_t>(ids[i]);
    }
}

constexpr std::array<RelicId, 33> kOracleSeed1{{
    RelicId::STRAWBERRY, RelicId::NUNCHAKU, RelicId::PRESERVED_INSECT,
    RelicId::ANCHOR, RelicId::JUZU_BRACELET, RelicId::VAJRA,
    RelicId::CERAMIC_FISH, RelicId::DREAM_CATCHER, RelicId::BOOT,
    RelicId::PEN_NIB, RelicId::WAR_PAINT, RelicId::AKABEKO,
    RelicId::BAG_OF_MARBLES, RelicId::WHETSTONE, RelicId::RED_SKULL,
    RelicId::MEAL_TICKET, RelicId::LANTERN, RelicId::MAW_BANK,
    RelicId::TINY_CHEST, RelicId::SMILING_MASK, RelicId::HAPPY_FLOWER,
    RelicId::BLOOD_VIAL, RelicId::ODDLY_SMOOTH_STONE,
    RelicId::CENTENNIAL_PUZZLE, RelicId::BAG_OF_PREPARATION,
    RelicId::ART_OF_WAR, RelicId::TOY_ORNITHOPTER, RelicId::ORICHALCUM,
    RelicId::ANCIENT_TEA_SET, RelicId::REGAL_PILLOW, RelicId::OMAMORI,
    RelicId::POTION_BELT, RelicId::BRONZE_SCALES,
}};

constexpr std::array<RelicId, 33> kOracleSeed2{{
    RelicId::ODDLY_SMOOTH_STONE, RelicId::BAG_OF_PREPARATION,
    RelicId::POTION_BELT, RelicId::MAW_BANK, RelicId::STRAWBERRY,
    RelicId::TOY_ORNITHOPTER, RelicId::OMAMORI, RelicId::CERAMIC_FISH,
    RelicId::PEN_NIB, RelicId::ART_OF_WAR, RelicId::AKABEKO,
    RelicId::CENTENNIAL_PUZZLE, RelicId::BRONZE_SCALES, RelicId::VAJRA,
    RelicId::HAPPY_FLOWER, RelicId::PRESERVED_INSECT, RelicId::BOOT,
    RelicId::ANCHOR, RelicId::NUNCHAKU, RelicId::LANTERN,
    RelicId::REGAL_PILLOW, RelicId::DREAM_CATCHER,
    RelicId::ANCIENT_TEA_SET, RelicId::ORICHALCUM, RelicId::SMILING_MASK,
    RelicId::WHETSTONE, RelicId::JUZU_BRACELET, RelicId::BLOOD_VIAL,
    RelicId::WAR_PAINT, RelicId::BAG_OF_MARBLES, RelicId::TINY_CHEST,
    RelicId::MEAL_TICKET, RelicId::RED_SKULL,
}};

constexpr std::array<RelicId, 33> kOracleSeed3{{
    RelicId::CERAMIC_FISH, RelicId::ANCIENT_TEA_SET, RelicId::WHETSTONE,
    RelicId::BOOT, RelicId::ANCHOR, RelicId::SMILING_MASK,
    RelicId::MEAL_TICKET, RelicId::BAG_OF_MARBLES, RelicId::JUZU_BRACELET,
    RelicId::AKABEKO, RelicId::PEN_NIB, RelicId::REGAL_PILLOW,
    RelicId::BRONZE_SCALES, RelicId::ODDLY_SMOOTH_STONE,
    RelicId::CENTENNIAL_PUZZLE, RelicId::TINY_CHEST, RelicId::NUNCHAKU,
    RelicId::BAG_OF_PREPARATION, RelicId::POTION_BELT,
    RelicId::STRAWBERRY, RelicId::HAPPY_FLOWER, RelicId::OMAMORI,
    RelicId::LANTERN, RelicId::ART_OF_WAR, RelicId::WAR_PAINT,
    RelicId::PRESERVED_INSECT, RelicId::RED_SKULL, RelicId::ORICHALCUM,
    RelicId::DREAM_CATCHER, RelicId::MAW_BANK, RelicId::BLOOD_VIAL,
    RelicId::TOY_ORNITHOPTER, RelicId::VAJRA,
}};

// B3.25: the three live shuffled UNCOMMON pool orders (same b14_accept captures,
// oracle.relicPools.uncommon). The canonical pre-shuffle pool_order in
// relics.yaml was derived by inverting the JDK shuffle (relicRng draw #2)
// against these three arrays -- all three seeds agree on one pre-shuffle order,
// and re-shuffling it here must reproduce each capture exactly.
constexpr std::array<RelicId, 30> kOracleUncommonSeed1{{
    RelicId::TOXIC_EGG, RelicId::ETERNAL_FEATHER, RelicId::SINGING_BOWL,
    RelicId::QUESTION_CARD, RelicId::SHURIKEN, RelicId::BOTTLED_LIGHTNING,
    RelicId::PEAR, RelicId::MOLTEN_EGG, RelicId::LETTER_OPENER,
    RelicId::MUMMIFIED_HAND, RelicId::STRIKE_DUMMY, RelicId::DARKSTONE_PERIAPT,
    RelicId::MATRYOSHKA, RelicId::FROZEN_EGG, RelicId::ORNAMENTAL_FAN,
    RelicId::GREMLIN_HORN, RelicId::SUNDIAL, RelicId::BOTTLED_FLAME,
    RelicId::WHITE_BEAST_STATUE, RelicId::THE_COURIER,
    RelicId::SELF_FORMING_CLAY, RelicId::HORN_CLEAT, RelicId::BLUE_CANDLE,
    RelicId::PANTOGRAPH, RelicId::BOTTLED_TORNADO, RelicId::PAPER_PHROG,
    RelicId::MEAT_ON_THE_BONE, RelicId::KUNAI, RelicId::INK_BOTTLE,
    RelicId::MERCURY_HOURGLASS,
}};

constexpr std::array<RelicId, 30> kOracleUncommonSeed2{{
    RelicId::WHITE_BEAST_STATUE, RelicId::MERCURY_HOURGLASS,
    RelicId::MEAT_ON_THE_BONE, RelicId::BLUE_CANDLE, RelicId::ETERNAL_FEATHER,
    RelicId::ORNAMENTAL_FAN, RelicId::BOTTLED_TORNADO, RelicId::SHURIKEN,
    RelicId::SELF_FORMING_CLAY, RelicId::PEAR, RelicId::THE_COURIER,
    RelicId::TOXIC_EGG, RelicId::BOTTLED_LIGHTNING, RelicId::QUESTION_CARD,
    RelicId::KUNAI, RelicId::BOTTLED_FLAME, RelicId::DARKSTONE_PERIAPT,
    RelicId::MUMMIFIED_HAND, RelicId::LETTER_OPENER, RelicId::SUNDIAL,
    RelicId::FROZEN_EGG, RelicId::PANTOGRAPH, RelicId::GREMLIN_HORN,
    RelicId::MOLTEN_EGG, RelicId::INK_BOTTLE, RelicId::PAPER_PHROG,
    RelicId::MATRYOSHKA, RelicId::SINGING_BOWL, RelicId::HORN_CLEAT,
    RelicId::STRIKE_DUMMY,
}};

constexpr std::array<RelicId, 30> kOracleUncommonSeed3{{
    RelicId::MUMMIFIED_HAND, RelicId::INK_BOTTLE, RelicId::SELF_FORMING_CLAY,
    RelicId::DARKSTONE_PERIAPT, RelicId::MERCURY_HOURGLASS, RelicId::SHURIKEN,
    RelicId::BOTTLED_FLAME, RelicId::BOTTLED_LIGHTNING, RelicId::HORN_CLEAT,
    RelicId::MATRYOSHKA, RelicId::BLUE_CANDLE, RelicId::ETERNAL_FEATHER,
    RelicId::WHITE_BEAST_STATUE, RelicId::MOLTEN_EGG, RelicId::PAPER_PHROG,
    RelicId::TOXIC_EGG, RelicId::GREMLIN_HORN, RelicId::LETTER_OPENER,
    RelicId::QUESTION_CARD, RelicId::BOTTLED_TORNADO, RelicId::SUNDIAL,
    RelicId::SINGING_BOWL, RelicId::PEAR, RelicId::KUNAI, RelicId::THE_COURIER,
    RelicId::STRIKE_DUMMY, RelicId::PANTOGRAPH, RelicId::FROZEN_EGG,
    RelicId::ORNAMENTAL_FAN, RelicId::MEAT_ON_THE_BONE,
}};

// B3.26: three live shuffled RARE and SHOP orders. Captain's Wheel appears in
// the rare source enumeration even though the task prose omitted it. Inverting
// all six captures produced one canonical pool_order per tier; re-shuffling the
// registry rows below reproduces the captures exactly.
constexpr std::array<RelicId, 28> kOracleRareSeed1{{
    RelicId::MAGIC_FLOWER, RelicId::FOSSILIZED_HELIX, RelicId::OLD_COIN,
    RelicId::DEAD_BRANCH, RelicId::CHAMPION_BELT, RelicId::PEACE_PIPE,
    RelicId::CHARONS_ASHES, RelicId::INCENSE_BURNER, RelicId::TUNGSTEN_ROD,
    RelicId::UNCEASING_TOP, RelicId::GIRYA, RelicId::ICE_CREAM,
    RelicId::POCKETWATCH, RelicId::CAPTAINS_WHEEL, RelicId::CALIPERS,
    RelicId::DU_VU_DOLL, RelicId::THREAD_AND_NEEDLE, RelicId::GINGER,
    RelicId::SHOVEL, RelicId::STONE_CALENDAR, RelicId::TURNIP,
    RelicId::GAMBLING_CHIP, RelicId::WING_BOOTS, RelicId::PRAYER_WHEEL,
    RelicId::BIRD_FACED_URN, RelicId::TORII, RelicId::LIZARD_TAIL,
    RelicId::MANGO,
}};
constexpr std::array<RelicId, 28> kOracleRareSeed2{{
    RelicId::PRAYER_WHEEL, RelicId::TUNGSTEN_ROD, RelicId::CAPTAINS_WHEEL,
    RelicId::TURNIP, RelicId::SHOVEL, RelicId::ICE_CREAM, RelicId::TORII,
    RelicId::PEACE_PIPE, RelicId::CHAMPION_BELT, RelicId::MAGIC_FLOWER,
    RelicId::GAMBLING_CHIP, RelicId::LIZARD_TAIL, RelicId::GINGER,
    RelicId::CALIPERS, RelicId::DEAD_BRANCH, RelicId::WING_BOOTS,
    RelicId::INCENSE_BURNER, RelicId::STONE_CALENDAR, RelicId::POCKETWATCH,
    RelicId::GIRYA, RelicId::MANGO, RelicId::FOSSILIZED_HELIX,
    RelicId::THREAD_AND_NEEDLE, RelicId::BIRD_FACED_URN,
    RelicId::UNCEASING_TOP, RelicId::OLD_COIN, RelicId::DU_VU_DOLL,
    RelicId::CHARONS_ASHES,
}};
constexpr std::array<RelicId, 28> kOracleRareSeed3{{
    RelicId::GINGER, RelicId::SHOVEL, RelicId::MANGO, RelicId::DU_VU_DOLL,
    RelicId::STONE_CALENDAR, RelicId::GAMBLING_CHIP,
    RelicId::BIRD_FACED_URN, RelicId::CHARONS_ASHES, RelicId::MAGIC_FLOWER,
    RelicId::WING_BOOTS, RelicId::TURNIP, RelicId::UNCEASING_TOP,
    RelicId::PEACE_PIPE, RelicId::CALIPERS, RelicId::POCKETWATCH,
    RelicId::CHAMPION_BELT, RelicId::ICE_CREAM, RelicId::CAPTAINS_WHEEL,
    RelicId::PRAYER_WHEEL, RelicId::THREAD_AND_NEEDLE, RelicId::GIRYA,
    RelicId::FOSSILIZED_HELIX, RelicId::INCENSE_BURNER,
    RelicId::TUNGSTEN_ROD, RelicId::OLD_COIN, RelicId::LIZARD_TAIL,
    RelicId::DEAD_BRANCH, RelicId::TORII,
}};

constexpr std::array<RelicId, 17> kOracleShopSeed1{{
    RelicId::ORRERY, RelicId::LEES_WAFFLE, RelicId::TOOLBOX,
    RelicId::CAULDRON, RelicId::SLING_OF_COURAGE, RelicId::ORANGE_PELLETS,
    RelicId::CLOCKWORK_SOUVENIR, RelicId::MEMBERSHIP_CARD,
    RelicId::PRISMATIC_SHARD, RelicId::THE_ABACUS, RelicId::FROZEN_EYE,
    RelicId::STRANGE_SPOON, RelicId::MEDICAL_KIT, RelicId::DOLLYS_MIRROR,
    RelicId::HAND_DRILL, RelicId::CHEMICAL_X, RelicId::BRIMSTONE,
}};
constexpr std::array<RelicId, 17> kOracleShopSeed2{{
    RelicId::ORANGE_PELLETS, RelicId::FROZEN_EYE,
    RelicId::SLING_OF_COURAGE, RelicId::DOLLYS_MIRROR, RelicId::HAND_DRILL,
    RelicId::PRISMATIC_SHARD, RelicId::BRIMSTONE, RelicId::STRANGE_SPOON,
    RelicId::ORRERY, RelicId::CLOCKWORK_SOUVENIR, RelicId::TOOLBOX,
    RelicId::THE_ABACUS, RelicId::CAULDRON, RelicId::MEDICAL_KIT,
    RelicId::CHEMICAL_X, RelicId::MEMBERSHIP_CARD, RelicId::LEES_WAFFLE,
}};
constexpr std::array<RelicId, 17> kOracleShopSeed3{{
    RelicId::MEDICAL_KIT, RelicId::ORRERY, RelicId::TOOLBOX,
    RelicId::MEMBERSHIP_CARD, RelicId::CLOCKWORK_SOUVENIR,
    RelicId::ORANGE_PELLETS, RelicId::LEES_WAFFLE,
    RelicId::PRISMATIC_SHARD, RelicId::THE_ABACUS, RelicId::BRIMSTONE,
    RelicId::SLING_OF_COURAGE, RelicId::CAULDRON, RelicId::CHEMICAL_X,
    RelicId::HAND_DRILL, RelicId::DOLLYS_MIRROR, RelicId::STRANGE_SPOON,
    RelicId::FROZEN_EYE,
}};

TEST(RelicPools, OracleCommonPoolOrdersMatchThreeLiveSeeds) {
    struct Case {
        int64_t seed;
        const std::array<RelicId, 33>* pool;
        int64_t s0;
        int64_t s1;
    };
    const Case cases[] = {
        {1790050543751LL, &kOracleSeed1, -6368056192266778531LL,
         -2945499761529171947LL},
        {1790050543752LL, &kOracleSeed2, -2647188671728073487LL,
         -7059635356477542313LL},
        {1790050543753LL, &kOracleSeed3, 5762858951679628331LL,
         -7642149939435051131LL},
    };
    for (const Case& c : cases) {
        RunState rs{};
        rs.relic_rng = from_seed(c.seed);
        initialize_relic_pools(rs);
        // B4.6's pinned oracle values, UNCHANGED by B3.25: the common shuffle
        // consumes relicRng draw #1 and the post-five-draw stream state is
        // independent of tier contents (all five draws are unconditional).
        expect_pool(rs, RelicPool::COMMON, *c.pool);
        EXPECT_EQ(rs.relic_rng.counter, 5);
        EXPECT_EQ(rs.relic_rng.s0, static_cast<uint64_t>(c.s0));
        EXPECT_EQ(rs.relic_rng.s1, static_cast<uint64_t>(c.s1));
        EXPECT_EQ(rs.relic_pool_count[static_cast<int>(RelicPool::BOSS)], 0)
            << "boss content belongs to B3.27";
    }
}

TEST(RelicPools, OracleUncommonPoolOrdersMatchThreeLiveSeeds) {
    struct Case {
        int64_t seed;
        const std::array<RelicId, 30>* pool;
    };
    const Case cases[] = {
        {1790050543751LL, &kOracleUncommonSeed1},
        {1790050543752LL, &kOracleUncommonSeed2},
        {1790050543753LL, &kOracleUncommonSeed3},
    };
    for (const Case& c : cases) {
        RunState rs{};
        rs.relic_rng = from_seed(c.seed);
        initialize_relic_pools(rs);
        expect_pool(rs, RelicPool::UNCOMMON, *c.pool);
        EXPECT_EQ(rs.relic_rng.counter, 5);
    }
}

TEST(RelicPools, OracleRareAndShopOrdersMatchThreeLiveSeeds) {
    struct Case {
        int64_t seed;
        const std::array<RelicId, 28>* rare;
        const std::array<RelicId, 17>* shop;
    };
    const Case cases[] = {
        {1790050543751LL, &kOracleRareSeed1, &kOracleShopSeed1},
        {1790050543752LL, &kOracleRareSeed2, &kOracleShopSeed2},
        {1790050543753LL, &kOracleRareSeed3, &kOracleShopSeed3},
    };
    for (const Case& c : cases) {
        RunState rs{};
        rs.relic_rng = from_seed(c.seed);
        initialize_relic_pools(rs);
        expect_pool(rs, RelicPool::RARE, *c.rare);
        expect_pool(rs, RelicPool::SHOP, *c.shop);
        EXPECT_EQ(rs.relic_rng.counter, 5);
    }
}

TEST(RelicPools, InitializesAllFiveWithFiveDrawsEvenWhenFourAreEmpty) {
    RunState rs{};
    rs.relic_rng = from_seed(77);
    RngStream expected = rs.relic_rng;
    for (int i = 0; i < 5; ++i) {
        (void)random_long(expected);
    }
    initialize_relic_pools(rs);
    EXPECT_EQ(rs.relic_pool_count[kCommon], 33);
    EXPECT_EQ(rs.relic_pool_count[static_cast<int>(RelicPool::RARE)], 28);
    EXPECT_EQ(rs.relic_pool_count[static_cast<int>(RelicPool::SHOP)], 17);
    EXPECT_EQ(rs.relic_rng.counter, 5);
    EXPECT_EQ(rs.relic_rng.s0, expected.s0);
    EXPECT_EQ(rs.relic_rng.s1, expected.s1);
}

TEST(RelicPools, Trap15FrontVsEndPopOppositeSides) {
    constexpr std::array ids{RelicId::ANCHOR, RelicId::BLOOD_VIAL,
                             RelicId::VAJRA};
    RunState front{};
    RunState end{};
    set_pool(front, RelicPool::COMMON, ids);
    set_pool(end, RelicPool::COMMON, ids);
    EXPECT_EQ(return_random_relic_key(front, RelicTier::COMMON), RelicId::ANCHOR);
    EXPECT_EQ(return_end_random_relic_key(end, RelicTier::COMMON), RelicId::VAJRA);
    EXPECT_EQ(front.relic_pool_count[kCommon], 2);
    EXPECT_EQ(end.relic_pool_count[kCommon], 2);
}

TEST(RelicPools, BossEndPathStillPopsFront) {
    constexpr std::array ids{RelicId::ANCHOR, RelicId::VAJRA};
    RunState rs{};
    set_pool(rs, RelicPool::BOSS, ids);
    EXPECT_EQ(return_end_random_relic_key(rs, RelicTier::BOSS), RelicId::ANCHOR);
}

TEST(RelicPools, FailedFrontCanSpawnRecheckSwitchesToEnd) {
    constexpr std::array ids{RelicId::TINY_CHEST, RelicId::BLOOD_VIAL,
                             RelicId::ANCHOR};
    RunState rs{};
    set_pool(rs, RelicPool::COMMON, ids);
    const RelicSpawnContext late{36, false, false};
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::COMMON, late),
              RelicId::ANCHOR);
    ASSERT_EQ(rs.relic_pool_count[kCommon], 1);
    EXPECT_EQ(rs.relic_pools[kCommon][0],
              static_cast<uint16_t>(RelicId::BLOOD_VIAL));
}

TEST(RelicPools, ExhaustedPoolsFallBackToCirclets) {
    RunState rs{};
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::RARE), RelicId::CIRCLET);
    EXPECT_EQ(return_end_random_relic_key(rs, RelicTier::BOSS),
              RelicId::CIRCLET);
    EXPECT_EQ(return_random_relic_key(rs, RelicTier::COMMON), RelicId::CIRCLET);
}

TEST(RelicPools, TierRollTableIsExactly50_33_17) {
    int common = 0;
    int uncommon = 0;
    int rare = 0;
    for (int roll = 0; roll < 100; ++roll) {
        switch (relic_tier_for_roll(roll)) {
            case RelicTier::COMMON: ++common; break;
            case RelicTier::UNCOMMON: ++uncommon; break;
            case RelicTier::RARE: ++rare; break;
            default: FAIL() << "unexpected tier";
        }
    }
    EXPECT_EQ(common, 50);
    EXPECT_EQ(uncommon, 33);
    EXPECT_EQ(rare, 17);
    EXPECT_EQ(relic_tier_for_roll(49), RelicTier::COMMON);
    EXPECT_EQ(relic_tier_for_roll(50), RelicTier::UNCOMMON);
    EXPECT_EQ(relic_tier_for_roll(82), RelicTier::UNCOMMON);
    EXPECT_EQ(relic_tier_for_roll(83), RelicTier::RARE);
}

TEST(RelicAcquisition, AppendsInOrderAndAppliesSheetEffects) {
    RunState rs{};
    rs.hp = 60;
    rs.max_hp = 80;
    rs.potion_slots = 2;
    RngStream misc = from_seed(1);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::STRAWBERRY),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::POTION_BELT),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(rs.relic_count, 2);
    EXPECT_EQ(rs.relics[0].relic_id, static_cast<uint16_t>(RelicId::STRAWBERRY));
    EXPECT_EQ(rs.relics[1].relic_id, static_cast<uint16_t>(RelicId::POTION_BELT));
    EXPECT_EQ(rs.hp, 67);
    EXPECT_EQ(rs.max_hp, 87);
    EXPECT_EQ(rs.potion_slots, 4);
}

TEST(RelicAcquisition, ConstructorAndOnEquipCountersAreExact) {
    RunState rs{};
    RngStream misc = from_seed(2);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::BURNING_BLOOD),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::OMAMORI),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::TINY_CHEST),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::NUNCHAKU),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.relics[0].counter, -1);
    EXPECT_EQ(rs.relics[1].counter, 2);
    EXPECT_EQ(rs.relics[2].counter, 0);
    EXPECT_EQ(rs.relics[3].counter, 0);
}

TEST(RelicAcquisition, OrdinaryDuplicatesAppendButCircletStacks) {
    RunState rs{};
    RngStream misc = from_seed(3);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.relic_count, 2);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(rs.relic_count, 3);
    EXPECT_EQ(rs.relics[2].counter, 1);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::CIRCLET_STACKED);
    EXPECT_EQ(rs.relic_count, 3);
    EXPECT_EQ(rs.relics[2].counter, 2);
}

TEST(RelicAcquisition, FixedRelicCapFailsWithoutMutation) {
    RunState rs{};
    RngStream misc = from_seed(4);
    for (int i = 0; i < kRelicCap; ++i) {
        ASSERT_EQ(acquire_relic(rs, misc, RelicId::ANCHOR),
                  RelicAcquireResult::ACQUIRED);
    }
    const int16_t hp = rs.hp;
    const int16_t max_hp = rs.max_hp;
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::STRAWBERRY),
              RelicAcquireResult::RELIC_CAP_REACHED);
    EXPECT_EQ(rs.relic_count, kRelicCap);
    EXPECT_EQ(rs.hp, hp);
    EXPECT_EQ(rs.max_hp, max_hp);
}

TEST(RelicAcquisition, WarPaintAndWhetstoneUseMiscRngJdkShuffle) {
    RunState rs{};
    constexpr CardId deck[] = {
        CardId::STRIKE, CardId::STRIKE, CardId::STRIKE, CardId::STRIKE,
        CardId::STRIKE, CardId::DEFEND, CardId::DEFEND, CardId::DEFEND,
        CardId::DEFEND, CardId::BASH,
    };
    rs.master_deck_count = 10;
    for (uint16_t i = 0; i < 10; ++i) {
        rs.master_deck[i].card_id = static_cast<uint16_t>(deck[i]);
    }
    RngStream misc = from_seed(1234);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::WAR_PAINT),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.master_deck[7].upgrade, 1);
    EXPECT_EQ(rs.master_deck[8].upgrade, 1);
    EXPECT_EQ(rs.master_deck[5].upgrade, 0);
    EXPECT_EQ(rs.master_deck[6].upgrade, 0);

    EXPECT_EQ(acquire_relic(rs, misc, RelicId::WHETSTONE),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.master_deck[4].upgrade, 1);
    EXPECT_EQ(rs.master_deck[0].upgrade, 1);
    EXPECT_EQ(rs.master_deck[1].upgrade, 0);
    EXPECT_EQ(rs.master_deck[9].upgrade, 0);
    EXPECT_EQ(misc.counter, 2);
}

TEST(RelicAcquisition, CircletCounterCapacityIsExplicit) {
    RunState rs{};
    RngStream misc = from_seed(5);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::ACQUIRED);
    rs.relics[0].counter = std::numeric_limits<int16_t>::max();
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::CIRCLET),
              RelicAcquireResult::COUNTER_CAP_REACHED);
    EXPECT_EQ(rs.relic_count, 1);
}

TEST(RelicPools, RunBeginPopulatesCommonPoolWithoutChangingFiveDrawOracle) {
    const RunController rc = run_begin(1790050543751LL, 20);
    expect_pool(rc.run, RelicPool::COMMON, kOracleSeed1);
    EXPECT_EQ(rc.run.relic_rng.counter, 5);
    ASSERT_EQ(rc.run.relic_count, 1);
    EXPECT_EQ(rc.run.relics[0].relic_id,
              static_cast<uint16_t>(RelicId::BURNING_BLOOD));
    EXPECT_EQ(rc.run.relics[0].counter, -1);
    // B3.25: the same run_begin also populates the uncommon pool.
    expect_pool(rc.run, RelicPool::UNCOMMON, kOracleUncommonSeed1);
}

// --- B3.25 canSpawn gates -----------------------------------------------------

TEST(RelicPools, UncommonCanSpawnFloorAndShopGates) {
    // "Settings.isEndless || floorNum <= 48" family (DarkstonePeriapt:44-46,
    // FrozenEgg2/MoltenEgg2/ToxicEgg2/MeatOnTheBone:53-55, QuestionCard:29-31,
    // SingingBowl:41-43).
    const RelicSpawnContext f48{48, false, false};
    const RelicSpawnContext f49{49, false, false};
    const RelicSpawnContext f49_endless{49, false, true};
    for (const RelicId id :
         {RelicId::DARKSTONE_PERIAPT, RelicId::FROZEN_EGG,
          RelicId::MEAT_ON_THE_BONE, RelicId::MOLTEN_EGG,
          RelicId::QUESTION_CARD, RelicId::SINGING_BOWL, RelicId::TOXIC_EGG}) {
        EXPECT_TRUE(relic_can_spawn(id, f48));
        EXPECT_FALSE(relic_can_spawn(id, f49));
        EXPECT_TRUE(relic_can_spawn(id, f49_endless));
    }
    // Courier (Courier.java:41-43): floor <= 48 AND not currently in a shop.
    EXPECT_TRUE(relic_can_spawn(RelicId::THE_COURIER, f48));
    EXPECT_FALSE(relic_can_spawn(RelicId::THE_COURIER, f49));
    EXPECT_FALSE(relic_can_spawn(RelicId::THE_COURIER,
                                 RelicSpawnContext{10, true, false}));
    // Matryoshka (Matryoshka.java:59-61): floor <= 40.
    EXPECT_TRUE(relic_can_spawn(RelicId::MATRYOSHKA,
                                RelicSpawnContext{40, false, false}));
    EXPECT_FALSE(relic_can_spawn(RelicId::MATRYOSHKA,
                                 RelicSpawnContext{41, false, false}));
}

TEST(RelicPools, BottledTrioCanSpawnReadsDeckGatesEvenInEndless) {
    // BottledFlame/Lightning: any non-BASIC card of the type in the master deck
    // (the only BASIC red rows are Strike/Defend/Bash). BottledTornado: any
    // POWER card (none exist until B3.7). No Settings.isEndless clause in any of
    // the three canSpawn bodies -- the deck gate applies in Endless too.
    RunState rs{};
    rs.master_deck_count = 3;
    rs.master_deck[0].card_id = static_cast<uint16_t>(CardId::STRIKE);
    rs.master_deck[1].card_id = static_cast<uint16_t>(CardId::DEFEND);
    rs.master_deck[2].card_id = static_cast<uint16_t>(CardId::BASH);
    RelicSpawnContext ctx{};
    fill_deck_spawn_gates(rs, ctx);
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_FLAME, ctx))
        << "all-basic deck: Bash is BASIC rarity, not bottleable";
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_LIGHTNING, ctx));
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_TORNADO, ctx));
    ctx.endless = true;
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_FLAME, ctx))
        << "no endless bypass in the Bottled canSpawn bodies";

    // A non-basic attack (Cleave) unlocks Bottled Flame only.
    rs.master_deck_count = 4;
    rs.master_deck[3].card_id = static_cast<uint16_t>(CardId::CLEAVE);
    fill_deck_spawn_gates(rs, ctx);
    EXPECT_TRUE(relic_can_spawn(RelicId::BOTTLED_FLAME, ctx));
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_LIGHTNING, ctx));

    // A non-basic skill (Shrug It Off) unlocks Bottled Lightning.
    rs.master_deck[3].card_id = static_cast<uint16_t>(CardId::SHRUG_IT_OFF);
    fill_deck_spawn_gates(rs, ctx);
    EXPECT_FALSE(relic_can_spawn(RelicId::BOTTLED_FLAME, ctx));
    EXPECT_TRUE(relic_can_spawn(RelicId::BOTTLED_LIGHTNING, ctx));
}

// --- B3.25 acquisition / run-layer effects -------------------------------------

TEST(RelicAcquisition, PearGrantsTenMaxHpAndHeals) {
    RunState rs{};
    rs.hp = 60;
    rs.max_hp = 80;
    RngStream misc = from_seed(6);
    EXPECT_EQ(acquire_relic(rs, misc, RelicId::PEAR),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.max_hp, 90);
    EXPECT_EQ(rs.hp, 70) << "increaseMaxHp(10, true) heals the gained amount";
}

TEST(RunDeck, EggsUpgradeOnObtainByTypeAndDarkstoneRewardsCurses) {
    RunState rs{};
    rs.hp = 60;
    rs.max_hp = 80;
    RngStream misc = from_seed(7);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::MOLTEN_EGG),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::TOXIC_EGG),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::DARKSTONE_PERIAPT),
              RelicAcquireResult::ACQUIRED);

    // Molten Egg upgrades an obtained ATTACK...
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::CLEAVE));
    EXPECT_EQ(rs.master_deck[0].upgrade, 1);
    // ...Toxic Egg an obtained SKILL...
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::SHRUG_IT_OFF));
    EXPECT_EQ(rs.master_deck[1].upgrade, 1);
    // ...an already-upgraded obtain stays as-is (canUpgrade && !upgraded)...
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::CLEAVE, /*upgrade=*/1));
    EXPECT_EQ(rs.master_deck[2].upgrade, 1);
    // ...and a CURSE is not egg-upgraded but pays out Darkstone's +6 max HP
    // (increaseMaxHp(6, true): +6 max AND +6 current).
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::INJURY));
    EXPECT_EQ(rs.master_deck[3].upgrade, 0);
    EXPECT_EQ(rs.max_hp, 86);
    EXPECT_EQ(rs.hp, 66);
}

TEST(RunDeck, AddCardWithoutRelicsIsAPlainAppend) {
    RunState rs{};
    rs.hp = 60;
    rs.max_hp = 80;
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::CLEAVE));
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::INJURY));
    EXPECT_EQ(rs.master_deck_count, 2);
    EXPECT_EQ(rs.master_deck[0].upgrade, 0);
    EXPECT_EQ(rs.max_hp, 80);
    EXPECT_EQ(rs.hp, 60);
}

// --- B3.26 rare/shop run-layer behavior -------------------------------------

TEST(RelicAcquisitionRareShop, MangoOldCoinWaffleAndWingBootsAreExact) {
    RunState rs{};
    rs.hp = 50;
    rs.max_hp = 80;
    rs.gold = 99;
    RngStream misc = from_seed(8);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::MANGO),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.hp, 64);
    EXPECT_EQ(rs.max_hp, 94);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::OLD_COIN),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.gold, 399);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::LEES_WAFFLE),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.max_hp, 101);
    EXPECT_EQ(rs.hp, 101) << "Waffle heals to full after +7 max HP";
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::WING_BOOTS),
              RelicAcquireResult::ACQUIRED);
    EXPECT_EQ(rs.relics[3].counter, 3);
}

TEST(RunDeckRare, DuVuDollTracksEveryCurseAddAndRemove) {
    RunState rs{};
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::INJURY));
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::STRIKE));
    RngStream misc = from_seed(9);
    ASSERT_EQ(acquire_relic(rs, misc, RelicId::DU_VU_DOLL),
              RelicAcquireResult::ACQUIRED);
    ASSERT_EQ(rs.relic_count, 1);
    EXPECT_EQ(rs.relics[0].counter, 1) << "onEquip scans the existing deck";
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::REGRET));
    EXPECT_EQ(rs.relics[0].counter, 2);
    ASSERT_TRUE(add_card_to_master_deck(rs, CardId::CLEAVE));
    EXPECT_EQ(rs.relics[0].counter, 2);
    ASSERT_TRUE(remove_master_deck_card(rs, 0));  // remove Injury
    EXPECT_EQ(rs.relics[0].counter, 1);
    ASSERT_TRUE(remove_master_deck_card(rs, 2));  // remove Cleave
    EXPECT_EQ(rs.relics[0].counter, 1);
}

TEST(RelicPoolsRare, FloorShopAndCampfireSpawnGatesAreExact) {
    EXPECT_TRUE(relic_can_spawn(
        RelicId::OLD_COIN, RelicSpawnContext{48, false, false}));
    EXPECT_FALSE(relic_can_spawn(
        RelicId::OLD_COIN, RelicSpawnContext{49, false, false}));
    EXPECT_FALSE(relic_can_spawn(
        RelicId::OLD_COIN, RelicSpawnContext{10, true, false}));
    EXPECT_FALSE(relic_can_spawn(
        RelicId::OLD_COIN, RelicSpawnContext{99, true, true}));
    EXPECT_TRUE(relic_can_spawn(
        RelicId::OLD_COIN, RelicSpawnContext{99, false, true}));
    EXPECT_TRUE(relic_can_spawn(
        RelicId::PRAYER_WHEEL, RelicSpawnContext{48, false, false}));
    EXPECT_FALSE(relic_can_spawn(
        RelicId::PRAYER_WHEEL, RelicSpawnContext{49, false, false}));
    EXPECT_TRUE(relic_can_spawn(
        RelicId::WING_BOOTS, RelicSpawnContext{40, false, false}));
    EXPECT_FALSE(relic_can_spawn(
        RelicId::WING_BOOTS, RelicSpawnContext{41, false, false}));
    EXPECT_TRUE(relic_can_spawn(
        RelicId::WING_BOOTS, RelicSpawnContext{99, false, true}));

    RelicSpawnContext camp{};
    camp.floor = 47;
    camp.campfire_relic_count = 1;
    for (RelicId id : {RelicId::GIRYA, RelicId::PEACE_PIPE,
                       RelicId::SHOVEL}) {
        EXPECT_TRUE(relic_can_spawn(id, camp));
        camp.campfire_relic_count = 2;
        EXPECT_FALSE(relic_can_spawn(id, camp));
        camp.campfire_relic_count = 1;
        camp.floor = 48;
        EXPECT_FALSE(relic_can_spawn(id, camp));
        camp.floor = 47;
        camp.endless = true;
        camp.campfire_relic_count = 2;
        EXPECT_FALSE(relic_can_spawn(id, camp))
            << "Endless bypasses floor only, never the two-relic cap";
        camp.campfire_relic_count = 1;
        EXPECT_TRUE(relic_can_spawn(id, camp));
        camp.endless = false;
    }
}

TEST(RelicPoolsRare, FillSpawnContextCountsCampfireRelics) {
    RunState rs{};
    rs.relics[0].relic_id = static_cast<uint16_t>(RelicId::GIRYA);
    rs.relics[1].relic_id = static_cast<uint16_t>(RelicId::SHOVEL);
    rs.relics[2].relic_id = static_cast<uint16_t>(RelicId::ANCHOR);
    rs.relic_count = 3;
    RelicSpawnContext ctx{};
    fill_deck_spawn_gates(rs, ctx);
    EXPECT_EQ(ctx.campfire_relic_count, 2);
    EXPECT_FALSE(relic_can_spawn(RelicId::PEACE_PIPE, ctx));
}

}  // namespace
}  // namespace sts::engine
