#!/usr/bin/env python3
# Hand-derived fixture generator for B3.13 (Cultist AI + monster turn).
#
# An INDEPENDENT oracle: it re-derives the game's RNG primitive and the Cultist
# decision tree from scratch in Python (a SECOND implementation of the frozen
# spec, not a refactor of the C++), so a translation bug in the engine
# (include/sts/engine/monster_cultist.*) has a real chance of diverging here.
# Consumed at runtime by tests/cultist_test.cpp. One-time authoring step (not
# wired into CMake), mirroring gen_jaw_worm_fixture.py.
#
# Regen command (repo root, either environment):
#     python3 tests/fixtures/gen_cultist_fixture.py
# Reads the 32 seeds r0..r31 from tests/golden/seed_battery.txt; writes
# tests/fixtures/cultist_fixture.tsv next to this script. Deterministic.
#
# PROVENANCE (cross-checked vs D:\STS_BG_Mod\SlayTheSpireDecompiled):
#   RandomXS128 / Random wrapper: as in gen_jaw_worm_fixture.py (RNG unchanged).
#   HP: Cultist A7 setHp(50,56) at A20 (Cultist.java:59-60); one monsterHpRng draw.
#   getMove (Cultist.java:145-153): firstMove -> INCANTATION(3), then
#     DARK_STRIKE(1) forever. Deterministic -- rollMove draws aiRng.random(99) and
#     IGNORES it. init() rolls once before turn 1; takeTurn ends with an
#     unconditional RollMoveAction (Cultist.java:108).
#
# DRAW-COUNTING: init = decision #1 (forced Incantation; 1 aiRng.random(99) draw,
# IGNORED). Each of the 20 turns executes turn K then rolls decision #(K+1): 1
# aiRng.random(99) draw (value ignored -- deterministic tree, no tiebreaks). So
# aiRng.counter advances by exactly 1 per turn. monsterHpRng drawn once at init.

import os

MASK64 = (1 << 64) - 1
DARK_STRIKE, INCANTATION = 1, 3
NUM_SEEDS = 32
NUM_TURNS = 20


def u64(x):
    return x & MASK64


def to_i64(x):
    x &= MASK64
    return x - (1 << 64) if x >= (1 << 63) else x


def murmur3(x):
    x = u64(x)
    x ^= x >> 33
    x = u64(x * 0xFF51AFD7ED558CCD)
    x ^= x >> 33
    x = u64(x * 0xC4CEB9FE1A85EC53)
    x ^= x >> 33
    return x


class Rng:
    """RandomXS128 + the game's Random-wrapper draw counter."""

    def __init__(self, seed):
        seed_bits = 0x8000000000000000 if seed == 0 else u64(seed)
        s0 = murmur3(seed_bits)
        self.s0 = s0
        self.s1 = murmur3(s0)
        self.counter = 0

    def _next_long_bits(self):
        s1 = self.s0
        s0 = self.s1
        self.s0 = s0
        s1 ^= u64(s1 << 23)
        self.s1 = u64(s1 ^ s0 ^ (s1 >> 17) ^ (s0 >> 26))
        return u64(self.s1 + s0)

    def _next_long_n(self, n):
        un = n
        while True:
            bits = self._next_long_bits() >> 1
            value = bits % un
            check = u64(bits - value + (un - 1))
            if to_i64(check) >= 0:
                return value

    def random_int(self, range_):
        v = self._next_long_n(range_ + 1)
        self.counter += 1
        return v

    def random_range(self, start, end):
        v = start + self._next_long_n(end - start + 1)
        self.counter += 1
        return v


def load_seeds(battery_path):
    seeds = []
    with open(battery_path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            label, value = line.split("\t")
            if label.startswith("r"):
                seeds.append((label, int(value)))
    seeds.sort(key=lambda lv: int(lv[0][1:]))
    assert len(seeds) == NUM_SEEDS, f"expected {NUM_SEEDS} r* seeds, got {len(seeds)}"
    return seeds


def simulate(seed):
    ai = Rng(seed)
    hp_rng = Rng(seed)

    hp = hp_rng.random_range(50, 56)  # setHp(50,56): one inclusive draw

    ai.random_int(99)                 # init rollMove decision #1: drawn, IGNORED
    history = [INCANTATION]           # firstMove forces INCANTATION

    turns = []
    for _k in range(1, NUM_TURNS + 1):
        move_k = history[-1]          # turn k executes the current head
        ai.random_int(99)             # rollMove for decision #(k+1): drawn, IGNORED
        history.append(DARK_STRIKE)   # past firstMove -> always Dark Strike
        turns.append((move_k, ai.s0, ai.s1, ai.counter))

    return {
        "hp": hp,
        "hp_s0": hp_rng.s0,
        "hp_s1": hp_rng.s1,
        "hp_counter": hp_rng.counter,
        "turns": turns,
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(here, "..", ".."))
    battery = os.path.join(repo_root, "tests", "golden", "seed_battery.txt")
    out_path = os.path.join(here, "cultist_fixture.tsv")

    seeds = load_seeds(battery)

    lines = []
    lines.append("# Cultist A20 hand-derived fixture (task B3.13).")
    lines.append("# Generated by tests/fixtures/gen_cultist_fixture.py -- do not edit by hand.")
    lines.append("# Draw-counting: init = decision #1 (forced Incantation, 1 aiRng.random(99)")
    lines.append("# draw IGNORED). Each of the 20 turns executes turn K then rolls decision")
    lines.append("# #(K+1): 1 aiRng.random(99) draw (value ignored -- deterministic). aiRng.counter")
    lines.append("# advances by exactly 1 per turn. monsterHpRng drawn once at init (counter 1).")
    lines.append("# Move ids: DARK_STRIKE=1, INCANTATION=3. s0/s1 are unsigned decimal uint64.")
    lines.append("# Rows:")
    lines.append("#   seed\t<label>\t<seed_int64>")
    lines.append("#   hp\t<hp>\t<hprng_s0>\t<hprng_s1>\t<hprng_counter>")
    lines.append("#   turn\t<K>\t<move_id>\t<airng_s0>\t<airng_s1>\t<airng_counter>")
    for label, seed in seeds:
        r = simulate(seed)
        lines.append(f"seed\t{label}\t{seed}")
        lines.append(f"hp\t{r['hp']}\t{r['hp_s0']}\t{r['hp_s1']}\t{r['hp_counter']}")
        for k, (move, s0, s1, ctr) in enumerate(r["turns"], start=1):
            lines.append(f"turn\t{k}\t{move}\t{s0}\t{s1}\t{ctr}")

    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"wrote {out_path} ({len(seeds)} seeds x {NUM_TURNS} turns)")


if __name__ == "__main__":
    main()
